### PR TITLE
Fix and Improve some parts of code

### PR DESCRIPTION
**Pull request by Akash98Sky**
I really inspire your work on making this package on tmdb api.
I tried my best to contribute to it by fixing some error and make it work better :)
Thank you.

### CODE REVIEW

**Comment by Akash98Sky** [comment]
@Kerego commit 64a58f9 is a fix for an Exception as mentioned in that commit. (Recommended merge)
Other 2 commits are just to improve the quality of code, and up-to you to merge or not. 

* All the commits are reviewed and tested by me in a LINUX environment.

**Comment by Kerego** [comment]
Hello @Akash98Sky, thanks for your contributions, everything looks good, however in order to deploy this to dart pub there are two more files that need updates
- changelog.md (details of latest update)
- pubspec.yaml (increment the version)

**Comment by Akash98Sky** [comment]
Ok, I'll do that.

But what should be the next version?
Still a pre release version like : 0.0.10
Or a stable release as : 0.1

**Comment by Kerego** [comment]
Thanks @Akash98Sky for your contribution. 
I've published the latest version to the dart pub.
Regarding versioning, I would keep it below 0.1 at least until the all of the movie API is covered, and then increment the minor version as we add the Series, Actor, Discovery and other functionality.
Not sure when that will happen though, as before you started contributing the project was kind of on hold, and I am not sure when I will start doing Flutter again.

**Comment by Akash98Sky** [comment]
You are most welcome @Kerego :)

And regarding the project maintenance, that's fine, take your time. In the mean time, if possible, I'll try to add these missing functionalities to this project.
Thank you.

**Pull request merged**
